[build]
  # Define o diretório onde o código está localizado, neste caso, a pasta 'frontend'
  base = "frontend"

  # Comando para instalar as dependências e rodar o build
  command = "npm run deploy"  # Este comando chama o script 'deploy' no package.json

  # Diretório onde o Next.js gera os arquivos de build
  publish = "frontend/.next"
  
  # (Opcional) Variáveis de ambiente, se necessário
  # [build.environment]
  #   NODE_ENV = "production"
